import Head from 'next/head'
import Header from '../components/Header';
import MainNews from '../components/MainNews';
import News from '../components/News';
import FeaturedNews from '../components/FeaturedNews';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='px-4 pt-7 pb-20 xl:px-[10.3em] lg:pt-[5.5em] font-inter'>
        <Header/>
        <div className='md:flex md:gap-5'>
          <MainNews/>
          <News/>
        </div>
        <FeaturedNews/>
      </main>
    </div>
  )
}


